### PR TITLE
approved HIPE: Description of AnonCrypt and AuthCrypt

### PR DESCRIPTION
**Pull request by kdenhartog**
Signed-off-by: Kyle Den Hartog <kdenhar@gmail.com>

This is intended to capture a comment made by @vimmerru which excellently articulated how AnonCrypt and AuthCrypt currently worked. I wanted to add this as documentation for others to understand what is happening during this process.

### CODE REVIEW

**Comment by dhh1128** [comment]
I'm just noting that I read the HIPE and feel good about it.

**Comment by dbluhm** [comment]
I also think this is a great addition to our documents here.

**Comment by kdenhartog** [comment]
Keys used in step 4 for we're reversed. I just made a commit that switches them around.

**Comment by swcurran** [comment]
Ah...nice!  Just saw this - glad to see if covered!

**Comment by dhh1128** [comment]
This PR was approved for merging in today's maintainers call. However, it mingles authcrypt/anoncrypt description with some modifications of another HIPE about wire messages. That HIPE is not ready to merge yet.

To get the core ideas merged from this PR, I created a new PR that includes just Kyle's writing, not the back history on the wire protocol. That is PR #42, which I just merged. I am therefore closing this PR.

**Pull request closed without merging**
