### PR TITLE
Payment Decorator

### PR DESCRIPTION
**Pull request by TelegramSam**
Signed-off-by: Sam Curren <telegramsam@gmail.com>

### CODE REVIEW

**Comment by tmarkovski** [comment]
I would love to see more flexible format considering these use cases

- Ability to specify tax information in the price or other fees
- Support for existing payment methods PayPal, ApplePay, Amazon Payments
- Decorator support to specify multiple possible payment methods (I should have the option to  pay with sovrin tokens or paypal, etc).
- A way to specify method specific information, for example if PayPal or Venmo, I can specify the account payments must be made to, etc

Can we reuse (or try to be compatible with) the [Payment Request API](https://www.w3.org/TR/payment-request/) defined by the Web Payments Group?

**Comment by dhh1128** [comment]
@TelegramSam and @tmarkovski : Would you mind if I took a crack at converting this to an Aries RFC and addressing some of Tomislav's suggestions?

**Comment by tmarkovski** [comment]
> @TelegramSam and @tmarkovski : Would you mind if I took a crack at converting this to an Aries RFC and addressing some of Tomislav's suggestions?

@dhh1128 Please do. I'm happy to contribute and would love to see payment RFCs out for discussion.

**Comment by dhh1128** [comment]
This is now superseded by https://github.com/hyperledger/aries-rfcs/pull/75. @TelegramSam , can we close this PR?

**Comment by TelegramSam** [comment]
closed, per @dhh1128's note above.

**Pull request closed without merging**
