### PR TITLE
approved HIPE: indy repos

### PR DESCRIPTION
**Pull request by devin-fisher**
A new hipe that details the repos in the Indy Project.

### CODE REVIEW

**Comment by burdettadam** [comment]
[ rendered repo_hipe ](https://github.com/devin-fisher/indy-hipe/blob/repo_hipe/text/indy-git-repos/README.md)

**Comment by burdettadam** [comment]
This is a great HIPE and well needed. 
I would like to propose:
 - a different [description](https://github.com/burdettadam/indy-hipe/tree/repo_hipe/text/indy-git-repos#description-2), in the provided link, for indy-sdk. I particularly thought "[and other artifacts](https://github.com/devin-fisher/indy-hipe/blob/repo_hipe/text/indy-git-repos/README.md#description-2)" in indy-sdk description was ambiguous and not well fitting. 
- a different [description](https://github.com/burdettadam/indy-hipe/tree/repo_hipe/text/indy-git-repos#description-5) and [maintenance](https://github.com/burdettadam/indy-hipe/tree/repo_hipe/text/indy-git-repos#maintenance-5), in the provided links, for indy-agent. I only added information about the test suite. 
-  an indy-doc [entry](https://github.com/burdettadam/indy-hipe/tree/repo_hipe/text/indy-git-repos#indy-doc) to support [this](https://github.com/hyperledger/indy-hipe/pull/24) HIPE.

All of my suggestion can be found in my [pull request](https://github.com/devin-fisher/indy-hipe/pull/1) to this HIPE.

**Comment by devin-fisher** [comment]
@burdettadam Your PR is out of sync. Can you fix the merge issues in you PR so I can eval and merge it?

**Comment by burdettadam** [comment]
@devin-fisher, Done.

**Comment by nage** [comment]
All repos should have MAINTAINTERS.md files that are referenced instead of listing them inline (per the maintainers conversation).

**Comment by e-nem-y** [comment]
I've made some changes to the HIPE in the following PR: https://github.com/devin-fisher/indy-hipe/pull/3.

I changed some of the typos and repo descriptions along with changing the structure of the document to make it more readable (for me).

This is the summary of the changes:
- General structure of the HIPE document changed
- HISTORY sections removed
- Maintainance made into a separate section to avoid repetition

Take a look and tell me what you think
    Descriptions of certain repos changed
    Typos fixed

**Comment by e-nem-y** [comment]
I've made some additional modifications as per @devin-fisher comments.

**Pull request merged**
